language: cpp

jobs:
  include:
  - stage: Bionic AMD64 Build
    os: linux
    dist: bionic
    arch: amd64
    before_script: sudo apt-get update
    script: ls /usr/include && ./setup --no-install --silent
