language: cpp

jobs:
  include:
  - stage: Xenial AMD64 Build
    os: linux
    dist: xenial
    arch: amd64
    install: sudo apt-get update
    script: ./setup --no-install --silent
  - stage: Xenial ARM Build 
    os: linux
    dist: xenial
    arch: armhf
    install: sudo apt-get update
    script: ./setup --no-install --silent
