language: cpp

jobs:
  include:
  - stage: Xenial AMD64 Build
    os: linux
    dist: xenial
    arch: amd64
    before_install: sudo apt-get update
    install: sudo apt-get install g++ git cmake flex bison python3-venv python3-dev libncurses5-dev libbenchmark-dev libgtest-dev verilator
    script: ./setup --no-install --silent
