language: cpp

jobs:
  include:
  - stage: Builds
    os: linux
    dist: bionic
    arch: amd64
    before_script: sudo apt-get update 
    script: ./setup --no-install --silent
  - os: linux
    dist: bionic
    arch: armhf
    before_script: sudo apt-get update 
    script: ./setup --no-install --silent
  - os: osx
    arch: amd64
    script: ./setup --no-install --silent
  - stage: Coverage
    os: linux
    dist: bionic
    arch: amd64
    before_script: sudo apt-get update && sudo apt-get install lcov
    script: ./setup --no-install --coverage --silent
