language: cpp

jobs:
  include:
  - stage: Coverage
    name: Coverage
    os: linux
    dist: bionic
    arch: amd64
    before_script: sudo apt-get update && sudo apt-get install lcov
    script: ./setup --coverage --no-install --silent && sonar-scanner
    addons:
      sonarcloud:
        organization: cascade
  - stage: Builds
    name: Bionic AMD64 Build
    os: linux
    dist: bionic
    arch: amd64
    before_script: sudo apt-get update 
    script: ./setup --no-install --silent
  - name: Bionic ARM Build
    os: linux
    dist: bionic
    arch: armhf
    before_script: sudo apt-get update 
    script: ./setup --no-install --silent
  - name: OSX Build
    os: osx
    arch: amd64
    script: ./setup --no-install --silent
